//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace planes_prueba
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class planes_pruebaEntities3 : DbContext
    {
        public planes_pruebaEntities3()
            : base("name=planes_pruebaEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PPI_TBL_LIDER_PDS> PPI_TBL_LIDER_PDS { get; set; }
        public virtual DbSet<PPI_TBL_PLAN_PRUEBAS> PPI_TBL_PLAN_PRUEBAS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
