//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace planes_prueba
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPI_TBL_LIDER_PDS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PPI_TBL_LIDER_PDS()
        {
            this.PPI_TBL_PLAN_PRUEBAS = new HashSet<PPI_TBL_PLAN_PRUEBAS>();
            this.PPI_TBL_PLAN_PRUEBAS1 = new HashSet<PPI_TBL_PLAN_PRUEBAS>();
        }
    
        public long ID_LIDER_PDS { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PPI_TBL_PLAN_PRUEBAS> PPI_TBL_PLAN_PRUEBAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PPI_TBL_PLAN_PRUEBAS> PPI_TBL_PLAN_PRUEBAS1 { get; set; }
    }
}
